name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/action-setup@v6.1.0
      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      # Run below steps regardless of whether an earlier one failed
      - name: typecheck
        if: ${{ !cancelled() }}
        run: pnpm typecheck
      - name: format:check
        if: ${{ !cancelled() }}
        run: pnpm format:check
      - name: lint
        if: ${{ !cancelled() }}
        run: pnpm lint
      # Run below step if all previous steps succeeded
      - name: build
        run: pnpm build
